name: SCA Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk:
    runs-on: ubuntu-latest
    env:
      # pega os secrets do repositório (configure em: Settings > Secrets and variables > Actions)
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Instala dependências (usa ci se houver lockfile)
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Install Snyk CLI
        run: npm install -g snyk

      # Opcional: autenticar explicitamente (env SNYK_TOKEN já basta, mas deixa explícito)
      - name: Snyk auth
        run: snyk auth "${SNYK_TOKEN}"

      # Executa o teste; continua mesmo se achar vulnerabilidades para gerar/armazenar o relatório
      - name: Run Snyk to check for vulnerabilities
        id: snyk
        continue-on-error: true
        run: |
          # Gera JSON e SARIF para artefatos/integrações
          snyk test --all-projects \
            --json-file-output=snyk-report.json \
            --sarif-file-output=snyk-report.sarif

      - name: Upload Snyk Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: |
            snyk-report.json
            snyk-report.sarif

      # Notifica no Slack se o passo do Snyk falhou (vulns → exit code != 0)
      - name: Send Slack notification if vulnerabilities found
        if: steps.snyk.outcome == 'failure'
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"⚠️ Vulnerabilidade crítica/alta detectada nas dependências (Snyk). Ver detalhes no artefato: snyk-report."}' \
            "$SLACK_WEBHOOK_URL"

      # Opcional: falhar o job no final se houve vulnerabilidades (remova se não quiser quebrar o PR)
      - name: Fail if Snyk found issues (re-fail)
        if: steps.snyk.outcome == 'failure'
        run: exit 1
